<center><h1> CPE 4040: Homework 3</h1></center>

1. Write your answer in the cell provided under each question.
2. __You must write comments to explain your thoughts and earn full credit__.
3. __Show your execution result__.
4. Do your own work. __Do not copy-and-paste other people's (or Generative AI's) codes.__
5. Please do not use pandas since it is not covered yet.

### Submission:
 * __Submit this notebook file and the pdf version__ - remember to add your name in the filename.

In [20]:
import numpy as np

### Check your Numpy Version

In [21]:
np.version.version

'1.24.3'

<h3>Q1: Checker Board (10 Points)</h3>

In [22]:
block = np.array([[1, 0, 0], # Define a base 3x3 repeating block
                  [0, 1, 0],
                  [0, 0, 1]])

matrix = np.tile(block, (3, 3)) # Use np.tile to repeat the block to form the 9x9 matrix

print(matrix)

[[1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]]


<h3>Q2: Array Indexing and Slicing (12 Points) </h3>

#### Q2.1 Please convert this vector, `np.arange(48)`, into a 8x6 array, i.e, 8 rows and 6 columns. Let's call this array A.

In [23]:
vector = np.arange(48)
A = np.reshape(vector, (8,6))
print (A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


#### Q2.2 Write codes to extract the elements in columns 2, 3, and 5 from A.

In [24]:
two = (A[:,2]) # column 2
print (two)
three = (A[:,3]) # column 3
print (three)
five = (A[:,5]) # column 5
print (five)


[ 2  8 14 20 26 32 38 44]
[ 3  9 15 21 27 33 39 45]
[ 5 11 17 23 29 35 41 47]


#### Q2.3 Create a new 3x5 array, with elements from rows 6, 1, 3 of A (in that order). __Hint: use fancy indexing__

In [25]:
cols = [1,3,5]
tbf = (A[3:, cols])
print (tbf.reshape(3,5))

[[19 21 23 25 27]
 [29 31 33 35 37]
 [39 41 43 45 47]]


#### Q2.4 Write codes to extract four elements from A with the following indices (4,2), (5,0), (1,2), (3,3).

In [26]:
first = (A[4,2])
print (first)
second = (A[5,0])
print (second)
third = (A[1,2])
print (third)
fourth = (A[3,3])
print (fourth)

26
30
8
21


<h3>Q3: Array Processing (15 points)</h3>
<h4>Given a 9-by-9 matrix of random integers from 0 to 99:</h4>

In [27]:
np.random.seed(1)
arr = np.random.randint(100,size=(9,9))
print(arr)

[[37 12 72  9 75  5 79 64 16]
 [ 1 76 71  6 25 50 20 18 84]
 [11 28 29 14 50 68 87 87 94]
 [96 86 13  9  7 63 61 22 57]
 [ 1  0 60 81  8 88 13 47 72]
 [30 71  3 70 21 49 57  3 68]
 [24 43 76 26 52 80 41 82 15]
 [64 68 25 98 87  7 26 25 22]
 [ 9 67 23 27 37 57 83 38  8]]


<h4>Q3.1 Observe that each 9x9 matrix is essentially nine blocks of 3x3 matrix. Write a Python code to calculate the mean value for each of the 3x3 matrix.</h4>
<h4> Hint: use array slicing to index each of the 9 sub-block.</h4>

In [28]:
arrone = (arr[:3, :3]) #topleft 3x3
arrtwo = (arr[3:6, :3]) #middleleft 3x3
arrthree= (arr[6:9, :3]) #bottomleft 3x3
arrfour = (arr[:3, 3:6]) #topmiddle 3x3
arrfive = (arr[3:6, 3:6]) #middle 3x3
arrsix = (arr[6:9, 3:6]) #topmiddle 3x3
arrseven = (arr[:3, 6:9]) #topright 3x3
arreight = (arr[3:6, 6:9]) #middleright 3x3
arrnine = (arr[6:9, 6:9]) #bottomright 3x3
meanone = (arrone.sum())/9
print(meanone)
meantwo = (arrtwo.sum())/9
print(meantwo)
meanthree = (arrthree.sum())/9
print(meanthree)
meanfour = (arrfour.sum())/9
print(meanfour)
meanfive = (arrfive.sum())/9
print(meanfive)
meansix = (arrsix.sum())/9
print(meansix)
meanseven = (arrseven.sum())/9
print(meanseven)
meaneight = (arreight.sum())/9
print(meaneight)
meannine = (arrnine.sum())/9
print(meannine)

37.44444444444444
40.0
44.333333333333336
33.55555555555556
44.0
52.333333333333336
61.0
44.44444444444444
37.77777777777778


<h4>Q3.2 What is the maximum value in the array? What is the index of the maximum value?</h4>
<h4>Note: use argmax().

In [36]:
reshape = np.reshape(arr, (1,81))
sort = np.sort(reshape)
print (sort)
print (sort[0][80])

[[ 0  1  1  3  3  5  6  7  7  8  8  9  9  9 11 12 13 13 14 15 16 18 20 21
  22 22 23 24 25 25 25 26 26 27 28 29 30 37 37 38 41 43 47 49 50 50 52 57
  57 57 60 61 63 64 64 67 68 68 68 70 71 71 72 72 75 76 76 79 80 81 82 83
  84 86 87 87 87 88 94 96 98]]
98


<h3>Q4: Rolling Dices (20 Points)</h3>
    
Assume that you have a fair dice of six faces, that is, it is equally likely to get any of the 6 possible outcomes for one dice roll.

__Q4.1 (5 points): Applying the same method that we used for coin tosses, write a code to simulate the probability of occurrence for each of the 6 numbers. You will perform at least 1,000,000 rolls.__

The result should be presented as follows:
   * Number of 1's = 100,000. Probability = 16.67%
   * Number of 2's = 96,000. Probability = 16.0%
   * ......

In [46]:
n_roll=1000000

roll = np.random.randint(1,7, size=n_roll)

print(roll[:20])
one = ((roll == 1).sum())
two = ((roll == 2).sum())
three = ((roll == 3).sum())
four = ((roll == 4).sum())
five = ((roll == 5).sum())
six = ((roll == 6).sum())
print ("Number of 1's =", one, ". Probability =", (one/n_roll)*100)
print ("Number of 2's =", two, ". Probability =", (two/n_roll)*100)
print ("Number of 3's =", three, ". Probability =", (three/n_roll)*100)
print ("Number of 4's =", four, ". Probability =", (four/n_roll)*100)
print ("Number of 5's =", five, ". Probability =", (five/n_roll)*100)
print ("Number of 6's =", six, ". Probability =", (six/n_roll)*100)

[5 2 6 6 6 6 6 5 5 6 5 2 2 2 4 1 1 2 2 1]
Number of 1's = 166146 . Probability = 16.6146
Number of 2's = 166807 . Probability = 16.6807
Number of 3's = 166393 . Probability = 16.639300000000002
Number of 4's = 167080 . Probability = 16.708000000000002
Number of 5's = 166683 . Probability = 16.6683
Number of 6's = 166891 . Probability = 16.6891


__Q4.2 (7 points): Suppose you are rolling two dices and add the two numbers together. The possible 11 outcomes range from 2 (1+1) to 12 (6+6).__ 

Write a simulation of 1,000,000 trials to find out the probability for each of the 11 outcomes.

The result should be presented as follows:
   * Number of 2's = 14,000. Probability = 2.80%
   * Number of 3's = 27,800. Probability = 5.56%
   * .....

In [48]:
n_roll=1000000

roll1 = np.random.randint(1,7, size=n_roll)
roll2 = np.random.randint(1,7, size=n_roll)

print(roll[:20])
two = ((roll1 + roll2 == 2).sum())
three = ((roll1 + roll2 == 3).sum())
four = ((roll1 + roll2 == 4).sum())
five = ((roll1 + roll2 == 5).sum())
six = ((roll1 + roll2 == 6).sum())
seven = ((roll1 + roll2 == 7).sum())
eight = ((roll1 + roll2 == 8).sum())
nine = ((roll1 + roll2 == 9).sum())
ten = ((roll1 + roll2 == 10).sum())
eleven = ((roll1 + roll2 == 11).sum())
twelve = ((roll1 + roll2 == 12).sum())
print ("Number of 2's =", two, ". Probability =", (two/n_roll)*100)
print ("Number of 3's =", three, ". Probability =", (three/n_roll)*100)
print ("Number of 4's =", four, ". Probability =", (four/n_roll)*100)
print ("Number of 5's =", five, ". Probability =", (five/n_roll)*100)
print ("Number of 6's =", six, ". Probability =", (six/n_roll)*100)
print ("Number of 7's =", seven, ". Probability =", (seven/n_roll)*100)
print ("Number of 8's =", eight, ". Probability =", (eight/n_roll)*100)
print ("Number of 9's =", nine, ". Probability =", (nine/n_roll)*100)
print ("Number of 10's =", ten, ". Probability =", (ten/n_roll)*100)
print ("Number of 11's =", eleven, ". Probability =", (eleven/n_roll)*100)
print ("Number of 12's =", twelve, ". Probability =", (twelve/n_roll)*100)

[ 1  5  5  8  1  7 11 11  4 12  9  8  4 12  8  7  6 11  4  3]
Number of 2's = 27817 . Probability = 2.7817000000000003
Number of 3's = 55885 . Probability = 5.5885
Number of 4's = 83416 . Probability = 8.3416
Number of 5's = 110891 . Probability = 11.0891
Number of 6's = 138567 . Probability = 13.8567
Number of 7's = 167239 . Probability = 16.7239
Number of 8's = 138553 . Probability = 13.855300000000002
Number of 9's = 111108 . Probability = 11.1108
Number of 10's = 83527 . Probability = 8.3527
Number of 11's = 55327 . Probability = 5.5327
Number of 12's = 27670 . Probability = 2.767


__Q4.3 (8 points): Suppose you roll an uneven dice 5 times, what is the probability of getting '4' exactly 3 times? The probability for each face of the dice is as follows.__

      * P(1) = 0.10, P(2) = 0.15, P(3)=0.20, P(4) = 0.25, P(5) = 0.20, P(6) = 0.10

Write a simulation of 1,000,000 trials for the answer.

In [56]:
n_roll=1000000
n_times=3

draws=np.random.randint(1,7, size=(n_roll, n_times))

four = np.sum(draws.sum(axis=1) == 4)

probability = (four/n_roll) * 100

print ("The probability of 4 being rolled 3 times is ", probability)



The probability of 4 being rolled 3 times is  1.3957000000000002


<h3>Q5: Picking Marbles (20 Points)</h3>

__Q5.1 (10 points): You have a bag of 12 marbles, 6 are red, 4 are white, and 2 are blue. You randomly pick three marbles from the bag. What is the probability of drawing 1 red, 1 white, and 1 blue (in this order)? The theoretical result is 2/55 ~3.636%. Write a simulation of 100,000 trials to verify the answer.__ 

Hint: You can follow the steps here:
1. Create an array of 12 elements, bag = np.array(['r','r','r','r','r','r','w','w','w','w','b','b'])
2. Create the desired outcome of 3 marbels of red, white, and blue, bag3 = np.array(['r','w','b'])
3. For each of the trial, you use np.random.permutation() to shuffle the bag array
4. Create a Boolean array by comparing the first three elements of the shuffled array with the desired outcome.
5. If the values the Boolean array are all True --> you have a match

In [58]:
import numpy as np

# Set up the bag of marbles
bag = np.array(['r', 'r', 'r', 'r', 'r', 'r', 'w', 'w', 'w', 'w', 'b', 'b'])
bag3 = np.array(['r', 'w', 'b'])

# Number of trials
trials = 100000
matches = 0

# Run the simulation for 100,000 trials
for _ in range(trials):
    shuffled_bag = np.random.permutation(bag)
    if np.all(shuffled_bag[:3] == bag3):
        matches += 1

# Calculate the probability
probability = matches / trials
probability


0.03565

__Q5.2 (10 points) With the same bag, you again pick out three marbles. However, the order does not matter this time. What is the probability of drawing 1 red, 1 white, and 1 blue? The theoretical result is 12/55 ~21.82%. Write a simulation of 100,000 trials to verify the answer.__

Hint: This question is different from Q5.1 since the order of the drawing is not important as long as you have {r,w,b} in the outcome. You should look for another way to compare the desired outcome with the shuffled arrays.

In [60]:
# Number of trials
trials = 100000
matches = 0
bag = np.array(['r', 'r', 'r', 'r', 'r', 'r', 'w', 'w', 'w', 'w', 'b', 'b'])
# Run the simulation for 100,000 trials where the order does not matter
for _ in range(trials):
    # Shuffle the bag and pick the first three elements
    shuffled_bag = np.random.permutation(bag)
    # Sort the first three elements and compare with the sorted desired outcome
    if np.array_equal(np.sort(shuffled_bag[:3]), np.sort(bag3)):
        matches += 1

# Calculate the probability
probability_orderless = matches / trials
probability_orderless


0.21808

### Q6: Birthday Problem & Normal Distribution (23 Points)

__Q6.1 (8 points) With 30 people in the same room, what is the probability that at least three people are sharing the same birthday? Write a simulation of 100,000 trials to find the answer.__

In [ ]:
def simulate_birthdays(num_people, num_trials):
    birthdays = np.random.randint(1, 366, (num_trials, num_people))
    shared_birthdays = np.sum(np.max(np.eye(366)[birthdays], axis=1) >= 3, axis=1)
    return np.mean(shared_birthdays)

num_people = 30
num_trials = 100000

probability = simulate_birthdays(num_people, num_trials)
print(f"Probability of at least 3 people sharing a birthday in a room of {num_people}:")
print(f"{probability:.4f} or {probability*100:.2f}%")

__Q6.2 (8 points) With 30 people in the same room, what is the probability that Exactly three people are sharing the same birthday? Write a simulation of 100,000 trials to find the answer.__

In [ ]:
def simulate_birthdays(num_people, num_trials):
    birthdays = np.random.randint(1, 366, (num_trials, num_people))
    
    # Count occurrences of each birthday
    counts = np.apply_along_axis(lambda x: np.bincount(x, minlength=366), axis=1, arr=birthdays)
    
    # Check for exactly one birthday with exactly three people
    exactly_three = np.sum(counts == 3, axis=1) == 1
    no_more_than_three = np.all(counts <= 3, axis=1)
    
    matches = np.logical_and(exactly_three, no_more_than_three)
    return np.mean(matches)

num_people = 30
num_trials = 100000

probability = simulate_birthdays(num_people, num_trials)
print(f"Probability of exactly 3 people sharing the same birthday in a room of {num_people}:")
print(f"{probability:.6f} or {probability*100:.4f}%")

__Q6.3 (7 poins) A company produces light bulbs, and the weight of each bulb is normally distributed with a mean of 50 grams and a standard deviation of 2 grams. If the company wants to package the bulbs in boxes of 10, what is the probability that the total weight of the bulbs in a box is between 495 and 505 grams? Write a simulation of 100,000 trials to answer this.__

In [ ]:
import numpy as np

def simulate_lightbulb_boxes(num_bulbs_per_box, num_boxes, mean_weight, std_weight, lower_limit, upper_limit):
    # Generate weights for all bulbs in all boxes
    bulb_weights = np.random.normal(mean_weight, std_weight, (num_boxes, num_bulbs_per_box))
    
    # Calculate total weight of each box
    box_weights = np.sum(bulb_weights, axis=1)
    
    # Count boxes within the weight range
    boxes_in_range = np.sum((box_weights >= lower_limit) & (box_weights <= upper_limit))
    
    # Calculate probability
    probability = boxes_in_range / num_boxes
    
    return probability

# Set parameters
num_bulbs_per_box = 10
num_boxes = 100000
mean_weight = 50  # grams
std_weight = 2    # grams
lower_limit = 495 # grams
upper_limit = 505 # grams

# Run simulation
result = simulate_lightbulb_boxes(num_bulbs_per_box, num_boxes, mean_weight, std_weight, lower_limit, upper_limit)

print(f"Probability that a box of {num_bulbs_per_box} bulbs weighs between {lower_limit} and {upper_limit} grams:")
print(f"{result:.4f} or {result*100:.2f}%")